### REGISTRATION

POST http://localhost:3001/api/users/register HTTP/1.1 
Content-Type: application/json
    
    {
        "username": "username1",
        "password": "password"
    }

### LOGIN

POST http://localhost:3001/api/users/login HTTP/1.1
Content-Type: application/json
    
        {
            "username": "username1",
            "password": "password"
        }

### LOGOUT