### REGISTRATION

POST http://localhost:3001/api/users/register HTTP/1.1 
Content-Type: application/json
    
    {
        "username": "username1",
        "password": "password"
    }

### LOGIN

POST http://localhost:3001/api/users/login HTTP/1.1
Content-Type: application/json
    
        {
            "username": "username1",
            "password": "password"
        }

### GET DOCUMENT BY ID
GET http://localhost:3001/api/documents/11 HTTP/1.1
Content-Type: application/json

### UPDATE DOCUMENT
PUT http://localhost:3001/api/documents/11 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzMyMDIyOTA3LCJleHAiOjE3MzIwMjY1MDd9.KNByA56WTRBos-bFmNbtzWhNTf90-oz8HL3ggvS6bho
        
        {
                "title": "PROVA",
                "scaleType": "Text",
                "scaleValue": null,
                "issuanceDate": "1900-01-01",
                "type": "Design Document",
                "language": "",
                "pages": "",
                "description": "Controllare georeference, add a connection",
                "allMunicipality": true,
                "latitude": "67.85812179",
                "longitude": "20.20992477",
                "stakeholders": [
                {
                    "id": 1,
                    "name": "LKAB",
                    "color": "#000000"
                }
                ],
                "connections": []
        }